### ISSUE TITLE
Names of features

### ISSUE THREAD

**Issue by MarinaParr** [mrzResearchArena/PyFeat#3]
Hello!
I would like to use the PyFeat tool to see which features are the most different between two sets of sequences. I created the optimumDataset.csv. But how to know which feature is where? There are only numbers in selectedIndex. 

Kind regards,
Marina Parr

**Comment by mrzResearchArena** [comment]
Unfortunately, our PyFeat tool can't show it. Thank you for raising the valuable issue. I will resolve the issue in the coming version of PyFeat.

-- Rafsanjani
