### ISSUE TITLE
Is the label file compulsory?

### ISSUE THREAD

**Issue by Alikerin** [mrzResearchArena/PyFeat#4]
I want to generate features from some test sequences that I don't know their labels. How do I use PyFeat for this?

**Comment by mrzResearchArena** [comment]
Yes, the labels are compulsory for the PyFeat tool. However, I resolve the issue and recreate the tool, named PyFeat-2.x.
You can easily find it from the given URL (https://github.com/mrzResearchArena/pyfeat-2.x).

Thanks,
Rafsanjani
